all: fibonacci_recursive.c  fibonacci_recursive_dynamic.c
	gcc fibonacci_recursive.c -o fibonacci_recursive
	gcc -std=c99 fibonacci_recursive_dynamic.c -o fibonacci_recursive_dynamic
	gcc -std=c99 fibonacci_nonrecursive.c -o fibonacci_nonrecursive 
